/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminUserManagementRouteRouteImport } from './routes/admin/user-management/route'
import { Route as AdminRbacRouteRouteImport } from './routes/admin/rbac/route'
import { Route as AdminAuditLogRouteRouteImport } from './routes/admin/audit-log/route'
import { Route as AdminAuditLogIndexRouteImport } from './routes/admin/audit-log/index'
import { Route as AdminUserManagementPrRouteImport } from './routes/admin/user-management/pr'
import { Route as AdminUserManagementOutletRouteImport } from './routes/admin/user-management/outlet'
import { Route as AdminUserManagementAgencyRouteImport } from './routes/admin/user-management/agency'
import { Route as AdminUserManagementAdminRouteImport } from './routes/admin/user-management/admin'
import { Route as AdminRbacRoleRouteImport } from './routes/admin/rbac/role'
import { Route as AdminRbacPermissionRouteImport } from './routes/admin/rbac/permission'
import { Route as AdminRbacModuleRouteImport } from './routes/admin/rbac/module'
import { Route as AdminAuditLogRoleRouteImport } from './routes/admin/audit-log/$role'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserManagementRouteRoute =
  AdminUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRbacRouteRoute = AdminRbacRouteRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRouteRoute = AdminAuditLogRouteRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogIndexRoute = AdminAuditLogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuditLogRouteRoute,
} as any)
const AdminUserManagementPrRoute = AdminUserManagementPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => AdminUserManagementRouteRoute,
} as any)
const AdminUserManagementOutletRoute =
  AdminUserManagementOutletRouteImport.update({
    id: '/outlet',
    path: '/outlet',
    getParentRoute: () => AdminUserManagementRouteRoute,
  } as any)
const AdminUserManagementAgencyRoute =
  AdminUserManagementAgencyRouteImport.update({
    id: '/agency',
    path: '/agency',
    getParentRoute: () => AdminUserManagementRouteRoute,
  } as any)
const AdminUserManagementAdminRoute =
  AdminUserManagementAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AdminUserManagementRouteRoute,
  } as any)
const AdminRbacRoleRoute = AdminRbacRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminRbacPermissionRoute = AdminRbacPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminRbacModuleRoute = AdminRbacModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminAuditLogRoleRoute = AdminAuditLogRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => AdminAuditLogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRouteRouteWithChildren
  '/admin/rbac': typeof AdminRbacRouteRouteWithChildren
  '/admin/user-management': typeof AdminUserManagementRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/audit-log/$role': typeof AdminAuditLogRoleRoute
  '/admin/rbac/module': typeof AdminRbacModuleRoute
  '/admin/rbac/permission': typeof AdminRbacPermissionRoute
  '/admin/rbac/role': typeof AdminRbacRoleRoute
  '/admin/user-management/admin': typeof AdminUserManagementAdminRoute
  '/admin/user-management/agency': typeof AdminUserManagementAgencyRoute
  '/admin/user-management/outlet': typeof AdminUserManagementOutletRoute
  '/admin/user-management/pr': typeof AdminUserManagementPrRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/rbac': typeof AdminRbacRouteRouteWithChildren
  '/admin/user-management': typeof AdminUserManagementRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/audit-log/$role': typeof AdminAuditLogRoleRoute
  '/admin/rbac/module': typeof AdminRbacModuleRoute
  '/admin/rbac/permission': typeof AdminRbacPermissionRoute
  '/admin/rbac/role': typeof AdminRbacRoleRoute
  '/admin/user-management/admin': typeof AdminUserManagementAdminRoute
  '/admin/user-management/agency': typeof AdminUserManagementAgencyRoute
  '/admin/user-management/outlet': typeof AdminUserManagementOutletRoute
  '/admin/user-management/pr': typeof AdminUserManagementPrRoute
  '/admin/audit-log': typeof AdminAuditLogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRouteRouteWithChildren
  '/admin/rbac': typeof AdminRbacRouteRouteWithChildren
  '/admin/user-management': typeof AdminUserManagementRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/audit-log/$role': typeof AdminAuditLogRoleRoute
  '/admin/rbac/module': typeof AdminRbacModuleRoute
  '/admin/rbac/permission': typeof AdminRbacPermissionRoute
  '/admin/rbac/role': typeof AdminRbacRoleRoute
  '/admin/user-management/admin': typeof AdminUserManagementAdminRoute
  '/admin/user-management/agency': typeof AdminUserManagementAgencyRoute
  '/admin/user-management/outlet': typeof AdminUserManagementOutletRoute
  '/admin/user-management/pr': typeof AdminUserManagementPrRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/audit-log'
    | '/admin/rbac'
    | '/admin/user-management'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/audit-log/$role'
    | '/admin/rbac/module'
    | '/admin/rbac/permission'
    | '/admin/rbac/role'
    | '/admin/user-management/admin'
    | '/admin/user-management/agency'
    | '/admin/user-management/outlet'
    | '/admin/user-management/pr'
    | '/admin/audit-log/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/rbac'
    | '/admin/user-management'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/audit-log/$role'
    | '/admin/rbac/module'
    | '/admin/rbac/permission'
    | '/admin/rbac/role'
    | '/admin/user-management/admin'
    | '/admin/user-management/agency'
    | '/admin/user-management/outlet'
    | '/admin/user-management/pr'
    | '/admin/audit-log'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/audit-log'
    | '/admin/rbac'
    | '/admin/user-management'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/audit-log/$role'
    | '/admin/rbac/module'
    | '/admin/rbac/permission'
    | '/admin/rbac/role'
    | '/admin/user-management/admin'
    | '/admin/user-management/agency'
    | '/admin/user-management/outlet'
    | '/admin/user-management/pr'
    | '/admin/audit-log/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log/': {
      id: '/admin/audit-log/'
      path: '/'
      fullPath: '/admin/audit-log/'
      preLoaderRoute: typeof AdminAuditLogIndexRouteImport
      parentRoute: typeof AdminAuditLogRouteRoute
    }
    '/admin/user-management/pr': {
      id: '/admin/user-management/pr'
      path: '/pr'
      fullPath: '/admin/user-management/pr'
      preLoaderRoute: typeof AdminUserManagementPrRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/user-management/outlet': {
      id: '/admin/user-management/outlet'
      path: '/outlet'
      fullPath: '/admin/user-management/outlet'
      preLoaderRoute: typeof AdminUserManagementOutletRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/user-management/agency': {
      id: '/admin/user-management/agency'
      path: '/agency'
      fullPath: '/admin/user-management/agency'
      preLoaderRoute: typeof AdminUserManagementAgencyRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/user-management/admin': {
      id: '/admin/user-management/admin'
      path: '/admin'
      fullPath: '/admin/user-management/admin'
      preLoaderRoute: typeof AdminUserManagementAdminRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/rbac/role': {
      id: '/admin/rbac/role'
      path: '/role'
      fullPath: '/admin/rbac/role'
      preLoaderRoute: typeof AdminRbacRoleRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/rbac/permission': {
      id: '/admin/rbac/permission'
      path: '/permission'
      fullPath: '/admin/rbac/permission'
      preLoaderRoute: typeof AdminRbacPermissionRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/rbac/module': {
      id: '/admin/rbac/module'
      path: '/module'
      fullPath: '/admin/rbac/module'
      preLoaderRoute: typeof AdminRbacModuleRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/audit-log/$role': {
      id: '/admin/audit-log/$role'
      path: '/$role'
      fullPath: '/admin/audit-log/$role'
      preLoaderRoute: typeof AdminAuditLogRoleRouteImport
      parentRoute: typeof AdminAuditLogRouteRoute
    }
  }
}

interface AdminAuditLogRouteRouteChildren {
  AdminAuditLogRoleRoute: typeof AdminAuditLogRoleRoute
  AdminAuditLogIndexRoute: typeof AdminAuditLogIndexRoute
}

const AdminAuditLogRouteRouteChildren: AdminAuditLogRouteRouteChildren = {
  AdminAuditLogRoleRoute: AdminAuditLogRoleRoute,
  AdminAuditLogIndexRoute: AdminAuditLogIndexRoute,
}

const AdminAuditLogRouteRouteWithChildren =
  AdminAuditLogRouteRoute._addFileChildren(AdminAuditLogRouteRouteChildren)

interface AdminRbacRouteRouteChildren {
  AdminRbacModuleRoute: typeof AdminRbacModuleRoute
  AdminRbacPermissionRoute: typeof AdminRbacPermissionRoute
  AdminRbacRoleRoute: typeof AdminRbacRoleRoute
}

const AdminRbacRouteRouteChildren: AdminRbacRouteRouteChildren = {
  AdminRbacModuleRoute: AdminRbacModuleRoute,
  AdminRbacPermissionRoute: AdminRbacPermissionRoute,
  AdminRbacRoleRoute: AdminRbacRoleRoute,
}

const AdminRbacRouteRouteWithChildren = AdminRbacRouteRoute._addFileChildren(
  AdminRbacRouteRouteChildren,
)

interface AdminUserManagementRouteRouteChildren {
  AdminUserManagementAdminRoute: typeof AdminUserManagementAdminRoute
  AdminUserManagementAgencyRoute: typeof AdminUserManagementAgencyRoute
  AdminUserManagementOutletRoute: typeof AdminUserManagementOutletRoute
  AdminUserManagementPrRoute: typeof AdminUserManagementPrRoute
}

const AdminUserManagementRouteRouteChildren: AdminUserManagementRouteRouteChildren =
  {
    AdminUserManagementAdminRoute: AdminUserManagementAdminRoute,
    AdminUserManagementAgencyRoute: AdminUserManagementAgencyRoute,
    AdminUserManagementOutletRoute: AdminUserManagementOutletRoute,
    AdminUserManagementPrRoute: AdminUserManagementPrRoute,
  }

const AdminUserManagementRouteRouteWithChildren =
  AdminUserManagementRouteRoute._addFileChildren(
    AdminUserManagementRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminAuditLogRouteRoute: typeof AdminAuditLogRouteRouteWithChildren
  AdminRbacRouteRoute: typeof AdminRbacRouteRouteWithChildren
  AdminUserManagementRouteRoute: typeof AdminUserManagementRouteRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogRouteRoute: AdminAuditLogRouteRouteWithChildren,
  AdminRbacRouteRoute: AdminRbacRouteRouteWithChildren,
  AdminUserManagementRouteRoute: AdminUserManagementRouteRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
